### ISSUE TITLE
SpigotCore -Phanatic

### ISSUE THREAD

**Issue by NightWolff9** [xXXIMMATTHEWXXx/PhanaticSpigotCore#2]
The SpigotCore is good, just add a configable message like when the player gets banned, their screen says something that we can config. Also, make sure when we /mute someone and /ban and /tempmute etc, that everyone can see the message in chat. Then it'll be perfect. Next MMV said we need a chat plugin like EssentialsChat but our own for PEX to work. Thanks

**Comment by xXXIMMATTHEWXXx** [comment]
Issue split. See:
https://github.com/xXXIMMATTHEWXXx/PhanaticSpigotCore/issues/3
https://github.com/xXXIMMATTHEWXXx/PhanaticSpigotCore/issues/4
https://github.com/xXXIMMATTHEWXXx/PhanaticSpigotCore/issues/5
