### ISSUE TITLE
SpigotCore- Customizable Ban Messages, Ban Errors.

### ISSUE THREAD

**Issue by NightWolff9** [xXXIMMATTHEWXXx/PhanaticSpigotCore#7]
Hey!
So I have uploaded the recent spigotcore you've sent me but there are still bugs. 

1. The prefix plugin doesn't work with PEX. But it works.
2. Players still can't see the /ban message in game. (GLOBAL FOR EVERYONE TO SEE).
3. When you ban someone, the person that got banned has a screen that says banned for whatever you typed. I want a pre set prefix set on the players screen when they get banned plus the message they got banned for. Example - Line 1-&c&l&uPUNISHMENT (Underlined)
                                                                           Line 2-&cYou've been banned! (if its a temp ban then just add"For: [time]")
                                                                           Line 3-&7Reason: &c(Reason)
                                                                           Line 4-&dUnfairly banned? Appeal at http://phanaticgames.com

That's all for now :)

**Comment by xXXIMMATTHEWXXx** [comment]
1) Prefix's will just need to be set via a command. Maybe on join? 
2) Do you mean over bungeecord?
3) Sure

**Comment by NightWolff9** [comment]
2. I mean in the server that they are in, everyone should be able to see the message including the person that is getting muted or banned or whatever.

Also another issue is that you can't ban players that are not online.

**Comment by NightWolff9** [comment]
2. Also if you'd like to add it over bungeecord that'll be fine too.

**Comment by xXXIMMATTHEWXXx** [comment]
The offline thing may be possible. It shoudl already go to everyone. Delete messages.yml and try

**Comment by xXXIMMATTHEWXXx** [comment]
All issues here have been solved. Closed.
