### ISSUE TITLE
SpigotCore-Commands

### ISSUE THREAD

**Issue by NightWolff9** [xXXIMMATTHEWXXx/PhanaticSpigotCore#8]
/sudo, /commandspy, /tpall, fix prefix update so when you do a /setrank, it'll update a player's rank AND prefix according to the rank, and can you block all commands that have a command and a ":" right next to them (no space ex /bukkit:pl /bukkit:? so it'll block any command that has a ":" in it)

**Comment by NightWolff9** [comment]
And also a /hub

**Comment by xXXIMMATTHEWXXx** [comment]
/sudo, /commandspy, /tpall, fix prefix update so when you do a /setrank, it'll update a player's rank AND prefix according to the rank, /hub

**Comment by xXXIMMATTHEWXXx** [comment]
Sudo done. Closed.
